server:
  port: 8080
  shutdown: graceful
  # NETTY ОПТИМИЗАЦИИ
  netty:
    connection-timeout: 30s
    idle-timeout: 120s
    max-initial-line-length: 65536
    max-header-size: 65536
    max-chunk-size: 65536
    initial-buffer-size: 65536

spring:
  application:
    name: payment-history-service

  # R2DBC КОНФИГ БУДЕТ ИЗ ПЕРЕМЕННЫХ ОКРУЖЕНИЯ

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  main:
    web-application-type: reactive
    banner-mode: "off"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        payment.mock.request.time: true
        payment.fetch.save.time: true
    tags:
      application: ${spring.application.name}
    enable:
      jvm: true
      logback: true
      system: true
      processor: true

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true

# Логирование
logging:
  level:
    com.example.payment: INFO
    org.springframework.r2dbc: WARN
    org.springframework.transaction: WARN
    reactor.netty: WARN
  pattern:
    level: "%5p"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15t] %-5level %40.40logger{40} - %msg%n"
  file:
    name: /tmp/payment-service.log