spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/payment_db
    username: payment_user
    password: payment_pass

mock:
  service:
    url: http://mock-payment-service:8081
reactor:
  netty:
    resources:
      max-connections: 2000
      max-idle-time: 120s